
services:
  backend:
    build:
        dockerfile: Dockerfile
        context: .
        target: development
    command: npm run start:debug
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    volumes:
      - .:/usr/src/
      - /usr/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db/pgData:/var/lib/postgresql/data