
services:
  backend:
    build:
        dockerfile: Dockerfile
        context: .
        target: development
#    command: npm run start:inspect
    command: npm run start:dev
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    volumes:
      - .:/usr/src/
      - /usr/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./db/pgData:/var/lib/postgresql/data