
services:
  backend:
    build:
        dockerfile: Dockerfile
        context: .
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
